### ISSUE TITLE
Astro support?

### ISSUE THREAD

**Issue by blimey85** [shuding/react-wrap-balancer#89]
I've been using this in my Next.js projects and it works great. I'm working on an Astro project right now and can't get it to work, even though I have React loaded into Astro. This is my first Astro project and from what I have read, some React stuff works and some doesn't with Astro.

**Comment by Xevion** [comment]
Hey, this just happened to me and managed to solve it.

```jsx
// The website states you should do this
import Balancer from "React-wrap-balancer";

// But it only worked if I did this
import { Balancer } from "react-wrap-balancer";
```

You can see where I solved it for my project on [this][blog-commit] commit.

[blog-commit]: https://github.com/Xevion/undefined.behavio.rs/commit/26526711ad73ca38c1fba11db3dc888fec1b6c41

**Comment by zaini** [comment]
Just calling out that I had a similar issue when using this library with react router v7

I'd get this error:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/home/zaini/hachi-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:5734:15)
    at retryNode (/home/zaini/hachi-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:5991:31)
    at renderNodeDestructive (/home/zaini/hachi-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:5941:11)
    at renderNode (/home/zaini/hachi-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:6398:18)
    at renderElement (/home/zaini/hachi-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:5358:18)
```

But I changed my import to:

```js
import { Balancer } from "react-wrap-balancer";
```

and it fixed the problem.
